baseurl: "https://xmag.netlify.app/" #"/" #"https://dvesti.github.io/mag/"
defaultContentLanguage: "ru"
languageCode: "ru-RU" #"en-us"
title:  "Dvesti" #"Dbecma"   #"Azbecmak"  #"Gazeta"
theme: "hugo-xmag"
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
preserveTaxonomyNames: true
footnotereturnlinkcontents: "↩"
hasCJKLanguage: true
enableEmoji: true

#paginate: 6
pagination:
  disableAliases: false
  pagerSize: 6
  path: page

outputs:
  home: ["html", "rss", "json"]
  
taxonomies:
  authors: authors       # multiple authors.
  tags: tags
  categories: categories  
  
blackfriday:
  extensionsmask: ["noIntraEmphasis"]  

permalinks:
  post: "/post/:year/:month/:day/:slug/"
  term:
    tags: "/tags/:slug/"
    categories: "/categories/:slug/"

menu:
  main:
    - name: Главная
      url: ""
      weight: 1
    - name: О блоге
      url: about/
      weight: 2
    - name: Категории
      url: categories/
      weight: 3
    - name: Тэги
      url: tags/
      weight: 4
#    - name: Поиск
#      url: search/
#      weight: 5  
    - name: Подписка
      url: index.xml

params:
  description: "A website built through Hugo and blogdown."
  footer: "&copy; [Dvesti](https://github.com/dvesti) 2024 | [Github](https://github.com/dvesti) | Powered by [Hugo](https://gohugo.io/). Theme: [XMag](https://github.com/yihui/hugo-xmag)"
  github_edit: "https://github.com/dvesti/mag/edit/main/content/"
  summary_length: 300
  categories:
    text:
      health: "Здоровье"
  text:
    back: "&larr; На Главную"
    edit: "Правка &rarr;"
    truncated: "&hellip;"
    comment: "Комментарии/Реакции"
    tags: "Тэги: "
    categories: "Категории: "
    example: "Пример"
    health: "Здоровье"
    statistics: "Статистика"
  favicon: "favicon.ico"
  banner: 
    src: "/img/dvesti-logo.jpg"
    alt:  "Dvesti"
    class: "center"
  logo:
    twitterImage: "/img/dvesti-logo.jpg"  

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
